### ISSUE TITLE
[BE] CREATE a user

### ISSUE THREAD

**Issue by LJ9332** [The-Sunken-Isles-First-Mate/first-mate-be#17]
# CREATE a user

## Details
- This endpoint should follow the pattern of `POST /api/v0/users` and should pass in a email, token, and uid as JSON in the body of the request.
- This endpoint will create a new user object
- A successful response will return a response with a 201 status code, and return the newly created user object
- If the email, token, or uid is missing in the request, a status code of 400, as well as a descriptive error message should be sent back in the response.
- If there already exists a User with that email or Uid, a response with a 422 status code and a message informing the client that that association already exists, should be sent back.

### Request: 
```
POST /api/v0/users
Content-Type: application/json  
Accept: application/json  
```

### Body:
```
{
     "email": "test@test.com",
     "token": "123hjhd8989enckn32kjkd",
     "uid": "1"
 }
```

### Response: ``` status: 201 ```  
```
{ 
  "data": {
    "id": "1",
    "type": "user"
    "attributes": {
       "email": "test@test.com",
       "token": "123hjhd8989enckn32kjkd",
       "uid": "1"
    }
  }
}
```

### Request:
```
POST /api/v0/users
Content-Type: application/json  
Accept: application/json  
```

### Body:
```
{
     "email": "test@test.com",
     "token": "123hjhd8989enckn32kjkd"
 }
```

### Response: ``` status: 400 ```  
```
[{
     "errors": [
         {
             "detail": "Validation failed: Uid can't be blank"
         }
     ]
 }
]
```

### Request:
```
POST /api/v0/users
Content-Type: application/json  
Accept: application/json  
```

### Body:
```
{
     "email": "test@test.com",
     "token": "123hjhd8989enckn32kjkd",
      "uid": "1"
 }
(where "test@test.com" and "1" are valid emails and uid's, but an existing User with those values already exists.)
```

### Response: ``` status: 422 ```  
```
[{
     "errors": [
         {
             "detail": "Validation failed: User with email="test@test.com" and uid=1 already exists"
         }
     ]
 }
]
```

**Comment by wallacebilly1** [comment]
This will likely change due to just using OAuth for log-in
